[workspace]
members = [
    "crates/analysis_ebur128",
    "crates/audio_rodio",
    "crates/domain",
    "crates/discord_presence",
    "crates/cli",
    "crates/analyzer",
    "crates/fingerprint",
    "crates/library_fs",
    "crates/library_service",
    "crates/library_worker",
    "crates/metadata_lofty",
    "crates/store_sqlite",
    "crates/playback_store_sqlite",
    "crates/engine",
    "crates/errors",
    "crates/app_ffi",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["NormalPlayer"]
